# Generated by Django 2.0.1 on 2018-05-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180515_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img_name',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
