# Generated by Django 2.0.1 on 2018-05-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_book_img_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='catalog',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
