# Generated by Django 2.0.1 on 2018-05-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180515_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.RemoveField(
            model_name='book',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='book',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='update_user',
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='Y', max_length=1),
        ),
    ]
