# Generated by Django 2.0.1 on 2018-05-14 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='job_title',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='identity',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='url',
        ),
    ]
