# Generated by Django 2.0.1 on 2018-04-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('book_link', models.TextField(max_length=255)),
                ('img_link', models.TextField(max_length=255)),
                ('book_name', models.TextField(max_length=255)),
            ],
        ),
    ]
