# Generated by Django 2.0.1 on 2018-05-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='parent',
        ),
    ]
